name: ShahidBeltPlugin
version: '1.0'
main: me.vanish.shahidBeltPlugin.Plugin
author: vanishgm
description: Плагин который добавляет в игру пояс шахида.
api-version: '1.21'
commands:
  createexplsion:
  shahidbelt:
    description: Gives the player a Shahid Belt.
    usage: /shahidbelt
    permission: shahidbelt.use
